runtime: python39

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  MODEL_PATH: "models/best_model_improved.h5"
  UPLOAD_FOLDER: "uploads"

instance_class: F2

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
